// React/lect3/day03/src/pages/ProductForm.jsx
import { useEffect, useState } from "react";
import { Button, Form } from "react-bootstrap";
import { addNewProduct, getProductById, editProduct } from '../api/productAPI'
import { useNavigate, useParams } from "react-router-dom";
export function ProductForm() {

    let [ formData, setFormData ] = useState( {
        productName: '',
        price: '',
        quantity: ''
    } )

    const navigate = useNavigate();

    const { id } = useParams();

    useEffect( () => {
        if ( id != 0 ) {


            getProductById( id ).then( response => {
                setFormData( response.data )
            } ).catch( error => {
                console.log( error )
            } )
        }
    }, [] )

    useEffect( () => {
        console.log( formData )
    }, [ formData ] )


    const formHandler = ( e ) => {
        setFormData( {
            ...formData,
            [ e.target.name ]: e.target.value
        } )
    }


    const addHandler = ( e ) => {
        e.preventDefault();
        if ( id == 0 ) {
            addNewProduct( formData ).then( () => {
                navigate( '/products' )
            } ).catch( error => {
                console.log( error )
            } )
        } else {
            editProduct( id, formData ).then( () => {
                navigate( '/products' )
            } ).catch( error => {
                console.log( error )
            } )
        }
    }
    return (
        <div className="container mt-3">
            <Form onSubmit={addHandler}>
                <Form.Group className="mb-3" controlId="formBasicEmail">
                    <Form.Label>Product Name</Form.Label>
                    <Form.Control
                        onChange={formHandler}
                        type="text"
                        placeholder="Enter Product Name"
                        name='productName'
                        value={formData.productName}

                    />
                    <Form.Text className="text-muted">
                        We'll never share your email with anyone else.
                    </Form.Text>
                </Form.Group>

                <Form.Group className="mb-3" controlId="formBasicPassword">
                    <Form.Label>Price</Form.Label>
                    <Form.Control


                        onChange={formHandler}
                        value={formData.price}

                        type="number" placeholder="Enter Price" name='price' />
                </Form.Group>
                <Form.Group className="mb-3" controlId="formBasicPassword">
                    <Form.Label>Quantity</Form.Label>
                    <Form.Control

                        value={formData.quantity}

                        onChange={formHandler} type="number" placeholder="Enter Quantity" name='quantity' />
                </Form.Group>

                <Button variant="dark" type="submit">
                    {id == 0 ? 'Add New Product' : 'Edit Product'}
                </Button>
            </Form>
        </div>
    )
}

// Angular/Day04/demo/src/app/components/products/product-form/product-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Iproduct } from '../../../models/iproduct';
import { productsList } from '../../../models/productsList';
import { ProductService } from '../../../services/product.service';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-product-form',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './product-form.component.html',
  styleUrl: './product-form.component.css',
})
export class ProductFormComponent implements OnInit {
  name: string = '';
  price: number = 0;
  quantity: number = 0;

  productId: any;
  product: any;
  constructor(
    public productServices: ProductService,
    public router: Router,
    public activatedRoute: ActivatedRoute
  ) {}
  ngOnInit(): void {
    this.productId = this.activatedRoute.snapshot.params['id'];
    if (this.productId != 0) {
      this.product = this.productServices.getProductById(this.productId);
      this.name = this.product.name;
      this.price = this.product.price;
      this.quantity = this.product.quantity;
    }
  }

  productHandler() {
    if (this.productId == 0) {
      let id = productsList.length + 1;
      let newProduct: Iproduct = {
        id,
        name: this.name,
        price: this.price,
        quantity: this.quantity,
      };
      this.productServices.addNewProduct(newProduct);
      this.router.navigate(['/products']);
    } else {
      // edit
      this.router.navigate(['/products']);
    }
  }
}

<div class="container mt-5">
  <h1 class="my-2 text-muted text-center">
    {{ productId == 0 ? "Add Product" : "Edit Product" }}
  </h1>
  <form (submit)="productHandler()">
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Product Name</label>
      <input
        type="text"
        name="productName"
        [(ngModel)]="name"
        class="form-control"
        id="exampleInputEmail1"
        aria-describedby="emailHelp"
        placeholder="Enter Product Name"
      />
      <div id="emailHelp" class="form-text">
        We'll never share your email with anyone else.
      </div>
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Price</label>
      <input
        type="number"
        name="price"
        [(ngModel)]="price"
        class="form-control"
        id="exampleInputPassword1"
        placeholder="Enter Product Price"
      />
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword6" class="form-label">Quantity</label>
      <input
        name="quantity"
        [(ngModel)]="quantity"
        type="number"
        class="form-control"
        id="exampleInputPassword6"
        placeholder="Enter Product Quantity"
      />
    </div>

    <button type="submit" class="btn btn-success">
      {{ productId == 0 ? "Add Product" : "Edit Product" }}
    </button>
  </form>
</div>
