// React/lect3/day03/src/pages/ProductDetails.jsx
import React, { useEffect, useState } from 'react'
import { Button } from 'react-bootstrap'
import { Link, useNavigate, useParams } from 'react-router-dom'


import { getProductById } from '../api/productAPI'


export function ProductDetails() {


    let [ product, setProduct ] = useState( {} )

    let [ isLoading, setIsLoading ] = useState( true )

    var navigate = useNavigate();

    const { id } = useParams();


    useEffect( () => {

        const fetchData = async () => {

            try {
                let response = await getProductById( id )
                console.log( response.data )
                setProduct( response.data )
                setIsLoading( false )
            } catch ( error ) {
                setIsLoading( false )
            }
        }

        fetchData()

    }, [] )
    const backToProducts = () => {

        navigate( '/products' )
    }
    return (
        <>

            {

                isLoading ?

                    <>

                        <h1 className='alert alert-dark'>Loading</h1>
                    </> :
                    <div className='bg-dark p-5 text-center text-light'>
                        <div className="container">


                            <h1>Product Details : {id}</h1>
                            <p className='lead'>Product Name : {product.productName}</p>
                            <p className='lead'>Product Name : {product.price}</p>
                            <button onClick={backToProducts} className='btn btn-success mt-4'>Back</button>
                        </div>


                    </div>
            }


        </>
    )
}

// Angular/Day04/demo/src/app/components/products/product-details/product-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ProductService } from '../../../services/product.service';
import { Iproduct } from '../../../models/iproduct';

@Component({
  selector: 'app-product-details',
  standalone: true,
  imports: [],
  templateUrl: './product-details.component.html',
  styleUrl: './product-details.component.css',
})
export class ProductDetailsComponent implements OnInit {
  productId: any;
  product?: Iproduct;
  constructor(
    public activatedRoute: ActivatedRoute,
    public productServices: ProductService,
    public router: Router
  ) {}
  ngOnInit(): void {
    this.productId = this.activatedRoute.snapshot.params['id'];
    this.product = this.productServices.getProductById(this.productId);
    console.log(this.product);
  }

  backToProducts() {
    this.router.navigate(['/products']);
  }
}

<div class="bg-dark p-5 text-center text-light">
  <h2>Product Details</h2>
  <div class="container">
    <p class="mt-2 lead fs-3">Product Name : {{ product?.name }}</p>
    <p class="mt-2 lead fs-4">Product Price : {{ product?.price }}</p>
    <p class="mt-2 lead fs-5">Product Quantity : {{ product?.quantity }}</p>
    <div>
      <i class="text-warning bi bi-star-fill"></i>
      <i class="text-warning bi bi-star-fill"></i>
      <i class="text-warning bi bi-star-fill"> </i>
      <i class="text-warning bi bi-star-fill"></i>
      <button (click)="backToProducts()" class="btn btn-success d-block">
        Back To Products
      </button>
    </div>
  </div>
</div>
