// Angular/Day04/demo/src/app/components/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductService } from '../../services/product.service';
import { Iproduct } from '../../models/iproduct';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './products.component.html',
  styleUrl: './products.component.css',
})
export class ProductsComponent implements OnInit {
  products: Iproduct[];
  constructor(public productService: ProductService) {
    this.products = [];
  }
  ngOnInit(): void {
    this.products = this.productService.getAllProducts();
  }

  deleteHandler(productId: number) {
    this.products = this.productService.deleteProduct(productId);
  }
}

<div class="mt-5 container">
  <h1 class="text-muted text-center">Our Products</h1>
  <div class="row mt-4">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Product Name</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let product of products">
          <th scope="row">{{ product.id }}</th>
          <td>{{ product.name }}</td>
          <td>{{ product.price | currency }}</td>
          <td>{{ product.quantity }}</td>
          <td>
            <i
              [routerLink]="['/products', product.id]"
              class="mx-1 fs-5 text-warning bi bi-eye-fill"
            ></i>
            <i
              [routerLink]="['/products', product.id, 'edit']"
              class="mx-1 fs-5 text-info bi bi-pencil-square"
            ></i>
            <i
              (click)="deleteHandler(product.id)"
              class="mx-1 fs-5 text-danger bi bi-trash3-fill"
            ></i>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// React/lect3/day03/src/pages/Products.jsx

import React, { useEffect, useState } from 'react'
import { Table } from 'react-bootstrap'
import { Link, useLoaderData } from 'react-router-dom'

import { getAllProducts, deleteProduct } from '../api/productAPI'
import { useDispatch, useSelector } from 'react-redux'

import { deleteProductAction, getAllProductsAction } from '../store/productSlice'
export function Products() {

    const dispatch = useDispatch();

    const { products, isLoading, error } = useSelector( state => state.productSlice )
    useEffect( () => {
        dispatch( getAllProductsAction() )

    }, [] )

    const deleteHandler = async ( productId ) => {

        dispatch( deleteProductAction( productId ) )
    }

    return (
        <div className='p-1 text-center mt-5'>
            <h1>Our Products</h1>
            <div className="container d-flex flex-column align-items-start">
                <Link to='/products/0/edit' className='mb-3'>

                    <i className="fs-3 m-2 bi bi-plus-circle-fill"></i>
                </Link>
                <Table striped bordered hover>
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Product Name</th>
                            <th>Price</th>
                            <th>quantity</th>
                            <th>actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {products && products.map( ( product ) => {
                            return (

                                <tr key={product.id}>
                                    <td>{product.id}</td>
                                    <td>{product.productName}</td>
                                    <td>{product.price}</td>
                                    <td>{product.quantity}</td>
                                    <td>

                                        <Link to={`/products/${product.id}`}>

                                            <i className="mx-2 text-warning fs-5 bi bi-eye-fill"></i>
                                        </Link>

                                        <Link to={`/products/${product.id}/edit`}>
                                            <i className="mx-2 text-info fs-5 bi bi-pencil-square"></i>
                                        </Link>
                                        <i onClick={() => deleteHandler( product.id )} className="mx-2 text-danger fs-5 bi bi-trash3-fill"></i>
                                    </td>
                                </tr>

                            )

                        } )}
                    </tbody>
                </Table>
            </div>
        </div>
    )
}
